import type { Category } from "../types/Category"
import {
  Calculator,
  FlaskConical,
  Languages,
  Bike,
  Palette,
  Atom,
  BookOpen,
  Scale,
  Code,
  Music,
  HeartPulse,
  TrendingUp,
  Brain,
  Globe,
} from "lucide-react";

export const CATEGORIES: Category[] = [
  { id: 1, name: "Matemáticas", icon: <Calculator size={40} />, color: "bg-blue-500" },
  { id: 2, name: "Biología", icon: <FlaskConical size={40} />, color: "bg-teal-500" },
  { id: 3, name: "Inglés", icon: <Languages size={40} />, color: "bg-indigo-500" },
  { id: 4, name: "Deporte", icon: <Bike size={40} />, color: "bg-orange-500" },
  { id: 5, name: "Arte", icon: <Palette size={40} />, color: "bg-purple-500" },
  { id: 6, name: "Física", icon: <Atom size={40} />, color: "bg-blue-600" },
  { id: 7, name: "Química", icon: <FlaskConical size={40} />, color: "bg-indigo-600" },
  { id: 8, name: "Historia", icon: <BookOpen size={40} />, color: "bg-emerald-600" },
  { id: 9, name: "Leyes", icon: <Scale size={40} />, color: "bg-slate-600" },
  { id: 10, name: "Programación", icon: <Code size={40} />, color: "bg-gray-800" },
  { id: 11, name: "Música", icon: <Music size={40} />, color: "bg-rose-500" },
  { id: 12, name: "Medicina", icon: <HeartPulse size={40} />, color: "bg-red-500" },
  { id: 13, name: "Economía", icon: <TrendingUp size={40} />, color: "bg-green-600" },
  { id: 14, name: "Psicología", icon: <Brain size={40} />, color: "bg-pink-500" },
  { id: 15, name: "Geografía", icon: <Globe size={40} />, color: "bg-cyan-600" },
]
